export const ACTION_TYPES = {
  SEARCH: 'SEARCH',
  UPDATE_INPUT: 'UPDATE_INPUT',
  UPDATE_RESULTS: 'UPDATE_RESULTS',
  DISPLAY_RECIPE: 'DISPLAY_RECIPE',
  SWITCH_INFO: 'SWITCH_INFO',
  SET_ERROR: 'SET_ERROR',
  DISPLAY_OPTIONS: 'DISPLAY_OPTIONS'
};